###
### Sudo required
###
dist: trusty
sudo: required


###
### Set language
###
language: python


###
### Python Build Matrix
###
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"


###
### Install required software
###
before_install:
  # Install required tools
  #- sudo apt-get update
  #- sudo apt-get install -y pep8 pylint


###
###
###
install:
  # Install
  - pip install -r requirements.txt
  - pip install pylint flake8 pep8
  # Show versions
  - pep8 --version   || true
  - flake8 --version || true
  - pylint --version || true


###
### Show versions
###
before_script:
  # Show versions
  - ./bin/coinwatch --help
  - ./bin/coinwatch --version


###
### Run tests
###
script:
  # Coding conventions
  - pep8 --max-line-length=100 bin/coinwatch
  #- if pylint --version >/dev/null 2>&1; then pylint bin/coinwatch; fi
  - if flake8 --version >/dev/null 2>&1; then flake8 --max-line-len=100 bin/coinwatch; fi
  # Run
  - ./bin/coinwatch -c example/config.yml
